# Generated by Django 4.0.3 on 2023-04-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singleton', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='days',
            new_name='drone_usage_days',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='hours',
            new_name='drone_usage_hours_by_day',
        ),
    ]
